name: device_application_flutter
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # web: ^0.5.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter: 
  plugin:
    platforms:
      android:
        package: global_corporation.general_developer.device_application_flutter
        pluginClass: DeviceApplicationFlutterPlugin
      # ios:
      #   pluginClass: DeviceApplicationFlutterPlugin
      # linux:
      #   pluginClass: DeviceApplicationFlutterPlugin
      # macos:
      #   pluginClass: DeviceApplicationFlutterPlugin
      # windows:
      #   pluginClass: DeviceApplicationFlutterPluginCApi
      # web:
      #   pluginClass: DeviceApplicationFlutterPluginWeb
      #   fileName: device_application_flutter_web.dart
 